// <auto-generated />
using System;
using Dexicon.Core.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dexicon.Core.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260916192617_ModelProfiles")]
    partial class ModelProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Dexicon.Core.Catalog.ApiToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TokenSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Blob", b =>
                {
                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Sha256");

                    b.ToTable("blobs", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.BlobText", b =>
                {
                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmptyReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractedChars")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExtractedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extractor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractorVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Sha256");

                    b.ToTable("blob_texts", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.ChunkSet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("BoundaryMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorpusId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomBoundaryPattern")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmbeddingDimensions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HeadingContext")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastIndexedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SentenceAware")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UnitAware")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CorpusId", "IsDefault");

                    b.HasIndex("CorpusId", "Name")
                        .IsUnique();

                    b.ToTable("chunk_sets", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Corpus", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastIndexedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("corpora", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.CorpusGrant", b =>
                {
                    b.Property<string>("CorpusId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("CorpusId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("corpus_grants", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.EmbeddingModelProfile", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Provider", "Model");

                    b.ToTable("model_profiles", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.FileChunkState", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChunkSetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IndexedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusDetail")
                        .HasColumnType("TEXT");

                    b.HasKey("FileId", "ChunkSetId");

                    b.HasIndex("ChunkSetId", "Status");

                    b.ToTable("file_chunk_states", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.IndexJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChunkSetId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunksWritten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorpusId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesTotal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QueuedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChunkSetId");

                    b.HasIndex("CorpusId", "StartedUtc");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.IndexedFile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractedChars")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlobSha256");

                    b.HasIndex("SourceId", "RelativePath")
                        .IsUnique();

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorpusId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcludeGlobs")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncludeGlobs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxFileBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseGitignore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CorpusId");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.ApiToken", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Tenant", "Tenant")
                        .WithMany("Tokens")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.BlobText", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Blob", "Blob")
                        .WithOne("Text")
                        .HasForeignKey("Dexicon.Core.Catalog.BlobText", "Sha256")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blob");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.ChunkSet", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Corpus", "Corpus")
                        .WithMany("ChunkSets")
                        .HasForeignKey("CorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corpus");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Corpus", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Tenant", "Tenant")
                        .WithMany("Corpora")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.CorpusGrant", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Corpus", "Corpus")
                        .WithMany("Grants")
                        .HasForeignKey("CorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dexicon.Core.Catalog.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corpus");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.FileChunkState", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.ChunkSet", "ChunkSet")
                        .WithMany("Files")
                        .HasForeignKey("ChunkSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dexicon.Core.Catalog.IndexedFile", "File")
                        .WithMany("ChunkStates")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChunkSet");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.IndexJob", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.ChunkSet", "ChunkSet")
                        .WithMany()
                        .HasForeignKey("ChunkSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dexicon.Core.Catalog.Corpus", "Corpus")
                        .WithMany("Jobs")
                        .HasForeignKey("CorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChunkSet");

                    b.Navigation("Corpus");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.IndexedFile", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Blob", "Blob")
                        .WithMany()
                        .HasForeignKey("BlobSha256")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dexicon.Core.Catalog.Source", "Source")
                        .WithMany("Files")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blob");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Source", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Corpus", "Corpus")
                        .WithMany("Sources")
                        .HasForeignKey("CorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corpus");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Blob", b =>
                {
                    b.Navigation("Text");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.ChunkSet", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Corpus", b =>
                {
                    b.Navigation("ChunkSets");

                    b.Navigation("Grants");

                    b.Navigation("Jobs");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.IndexedFile", b =>
                {
                    b.Navigation("ChunkStates");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Source", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Tenant", b =>
                {
                    b.Navigation("Corpora");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
