// <auto-generated />
using System;
using Dexicon.Core.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dexicon.Core.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Dexicon.Core.Catalog.ApiToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TokenSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Blob", b =>
                {
                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Sha256");

                    b.ToTable("blobs", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Corpus", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("BoundaryMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmbeddingDimensions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastIndexedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("corpora", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.CorpusGrant", b =>
                {
                    b.Property<string>("CorpusId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("CorpusId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("corpus_grants", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.IndexJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunksWritten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorpusId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesTotal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorpusId", "StartedUtc");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.IndexedFile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractedChars")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("IndexedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusDetail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "RelativePath")
                        .IsUnique();

                    b.HasIndex("SourceId", "Status");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorpusId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcludeGlobs")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncludeGlobs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxFileBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseGitignore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CorpusId");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.ApiToken", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Tenant", "Tenant")
                        .WithMany("Tokens")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Corpus", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Tenant", "Tenant")
                        .WithMany("Corpora")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.CorpusGrant", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Corpus", "Corpus")
                        .WithMany("Grants")
                        .HasForeignKey("CorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dexicon.Core.Catalog.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corpus");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.IndexJob", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Corpus", "Corpus")
                        .WithMany("Jobs")
                        .HasForeignKey("CorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corpus");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.IndexedFile", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Source", "Source")
                        .WithMany("Files")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Source", b =>
                {
                    b.HasOne("Dexicon.Core.Catalog.Corpus", "Corpus")
                        .WithMany("Sources")
                        .HasForeignKey("CorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corpus");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Corpus", b =>
                {
                    b.Navigation("Grants");

                    b.Navigation("Jobs");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Source", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Dexicon.Core.Catalog.Tenant", b =>
                {
                    b.Navigation("Corpora");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
